version: "3.9"

services:
  db_test:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: model_providers
    ports:
      - "15432:5432"
    volumes:
      - ../data/pgdata_test:/var/lib/postgresql/data

volumes:
  pgdata: