version: "3.9"

services:
  db:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: model_providers
    ports:
      - "5432:5432"
    volumes:
      - ../data/pgdata:/var/lib/postgresql/data

volumes:
  pgdata: